shellEmulator: true
trustPolicy: no-downgrade

allowBuilds:
  esbuild: true
  sharp: true
  workerd: true

catalogs:
  dev:
    '@astrojs/compiler-rs': ^0.1.10
    '@astrojs/mdx': ^5.0.4
    '@astrojs/partytown': ^2.1.7
    '@astrojs/rss': ^4.0.18
    '@astrojs/sitemap': ^3.7.2
    '@iconify/json': ^2.2.469
    '@unocss/astro': ^66.6.8
    astro: ^6.2.1
    astro-seo: ^1.1.0
    date-fns: ^4.1.0
    fast-xml-builder: ^1.1.5
    mdast-util-to-string: ^4.0.0
    react: ^19.2.5
    react-dom: ^19.2.5
    reading-time: ^1.5.0
    sharp: ^0.34.5
    takumi-js: ^1.1.2
    taze: ^19.11.0
    ufo: ^1.6.4
    unocss: ^66.6.8
    vfile: ^6.0.3
    wrangler: ^4.87.0
  lint:
    '@antfu/eslint-config': ^8.2.0
    '@unocss/eslint-plugin': ^66.6.8
    astro-eslint-parser: ^1.4.0
    eslint: ^10.3.0
    eslint-plugin-astro: ^1.7.0
    eslint-plugin-format: ^2.0.1
    prettier-plugin-astro: ^0.14.1
  types:
    '@types/mdast': ^4.0.4
    '@types/react': ^19.2.14
    '@types/react-dom': ^19.2.3
